### ISSUE TITLE
Never cache audio files?

### ISSUE THREAD

**Issue by jmazzahacks** [jamescridland/podinfra.net#10]
Perhaps this is fine advice for a desktop experience, but try doing customer service on a mobile app with no caching enabled.  You will get yelled at by your customers for multiple reasons, the most prominent two would be:

- You app uses too much bandwidth! (Especially bad for folks on metered plans)
- Your app keeps dropping the audio stream too often!

I'd suggest the -right way- to do this would be geo-targeting the RSS feed layer, and then using cache-control headers (which many apps will respect), more work on the hosting side for sure, but mobile app devs are in a competitive space and we need to keep our users happy.

Also, for "exotic" podcasts like the NPR example, perhaps a new P2.0 element that could instruct apps for special cache handling could also be an acceptable solution.

**Comment by jamescridland** [comment]
Hey, @jasonhudgins - thanks for this.

You're right - "never cache audio files" needs to be rewritten to make it a little more obvious. That means "please don't cache the audio file once in your own systems and just serve that to users" - always get a fresh copy of the audio each time you deliver it to a user.

Of course it can be locally cached/downloaded. I will go make that change now. Does that clear this up?

**Comment by jmazzahacks** [comment]
Yep, that helps a lot and makes sense, thanks James!
