### ISSUE TITLE
Tip for Season display

### ISSUE THREAD

**Issue by evoterra** [jamescridland/podinfra.net#5]
Under 2nd bullet, add:

_Tip_: Make it easy to navigate subsequent seasons. Some serial podcasts, like fiction podcasts, are designed to be listened to in _season_ order, as well as the correct order within a season.

**Comment by jamescridland** [comment]
This looks great, Evo.

You could submit this edit yourself by...

* Choosing the right file in https://github.com/jamescridland/podinfra.net/tree/main/app-developers
* Hitting the 'edit' pencil in the top right
* Edit away, and submit it as a pull request (it's relatively simple) when done.

But I'm also happy to edit the file for you. Just let me know!

**Comment by jamescridland** [comment]
(PS: I'm adding this, and playing with author credits)
