### ISSUE TITLE
Refer to <content:encoded> and <description> in Display descriptions properly

### ISSUE THREAD

**Issue by evoterra** [jamescridland/podinfra.net#6]
It may be worthwhile to draw the attention of devs to the fact that there may be differences in the <description> and the <conten:encoded>[CDATA[] field, along with what to expect.

I know that podcast hosting companies are VERY inconsistent, and I'm not sure how much direction this document should provide on what to use. But I suggest calling it out so they are aware and are evaluating both, perhaps?

**Comment by jamescridland** [comment]
Agree. I've added a line in there.
