### ISSUE TITLE
For publishers

### ISSUE THREAD

**Issue by staceygoers** [jamescridland/podinfra.net#9]
- If your episode or podcast is explicit, mark it as such in with your hosting provider/RSS feed.
- With your any of your text fields with your podcast -- episode title, podcast title, episode description, podcast description -- you should absolutely optimize for SEO, but don't keyword stuff.

**Comment by jamescridland** [comment]
Thank you! I kept these safe until I got round to starting a publishers section; but have added them to something temporary to kick us off.
